package com.mailerdaemon.app

const val FB_Collec_Club = "club"
const val FB_Collec_Notice = "Notices"
const val FB_Collec_Event = "Events"
const val FB_Collec_PLACEMENT = "Placement"
const val FB_Photos = "Photos"
const val FB_Club_Icons = "clubIcons"
const val FB_PAGE = "https://www.facebook.com/MDiitism"
const val No_Internet = "Problem getting data"
const val Done_Refresh = "Done, Refresh to see change"
const val FB_Lost_Found = "lost_n_found"
const val ADMIN_ID = "Pl4KwImyv9Ro5RQqlT3IqMwXwaH3"
const val AppLink = "https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=en"
const val TIME_NOTI = "time"
const val MESS_LINK = "https://drive.google.com/file/d/1F6WKYt3Sjeok9BCGXiPs7KYcVAbFIS3p/view?usp=sharing"
const val HOLIDAY_LINK = "https://drive.google.com/open?id=1vW3F_AuoMkxsOdCa9J9JAm2ZGnzuQzcz"
const val CALENDER_LINK = "https://drive.google.com/file/d/1htoFcIxqjQiYZH2LCTJuruqT1xRaoYKb/view?usp=sharing"
const val WARDEN_LINK = "https://drive.google.com/file/d/1kuXyrICNxOdtMt918cjxoZ7_g2NHciLM/view?usp=sharing"
