package com.mailerdaemon.app

const val INTRO = "intro"
const val NAME = "Name"
const val U_ID = "uid"
const val GENERAL = "GENERAL"
const val MAIN = "Main"
const val CHANNEL_ID = "id123"
const val FB_USER = "user"
const val ACCESS = "Access"
const val FB_CLUB = "club"
const val FB_NOTICE = "Notices"
const val FB_EVENT = "Events"
const val FB_PLACEMENT = "Placement"
const val FB_PHOTOS = "Photos"
const val FB_CLUB_ICON = "clubIcons"
const val FB_PAGE = "https://www.facebook.com/MDiitism"
const val NO_INTERNET = "Problem getting data"
const val DONE_REFRESH = "Done, Refresh to see change"
const val FB_LOST_FOUND = "lost_n_found"
const val ADMIN_ID = "Pl4KwImyv9Ro5RQqlT3IqMwXwaH3"
const val APP_LINK = "https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=en"
const val TIME_NOTI = "time"
const val MESS_LINK = "https://drive.google.com/file/d/1F6WKYt3Sjeok9BCGXiPs7KYcVAbFIS3p/view?usp=sharing"
const val HOLIDAY_LINK = "https://drive.google.com/open?id=1vW3F_AuoMkxsOdCa9J9JAm2ZGnzuQzcz"
const val CALENDER_LINK = "https://drive.google.com/file/d/1htoFcIxqjQiYZH2LCTJuruqT1xRaoYKb/view?usp=sharing"
const val WARDEN_LINK = "https://drive.google.com/file/d/1kuXyrICNxOdtMt918cjxoZ7_g2NHciLM/view?usp=sharing"
