package com.mailerdaemon.app

const val INTRO = "intro"
const val club_id = "club_id"
const val NAME = "Name"
const val U_ID = "uid"
const val GENERAL = "GENERAL"
const val MAIN = "Main"
const val CHANNEL_ID = "id123"
const val FB_USER = "user"
const val ACCESS = "Access"
const val FB_CLUB = "club"
const val FB_NOTICE = "Notices"
const val FB_EVENT = "Events"
const val FB_PLACEMENT = "Placement"
const val FB_PHOTOS = "Photos"
const val FB_CLUB_ICON = "clubIcons"
const val FB_PAGE = "https://www.facebook.com/MDiitism"
const val NO_INTERNET = "Problem getting data"
const val DONE_REFRESH = "Done, Refresh to see change"
const val FB_LOST_FOUND = "lost_n_found"
const val ADMIN_ID = "Pl4KwImyv9Ro5RQqlT3IqMwXwaH3"
const val APP_LINK = "https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=en"
const val TIME_NOTI = "time"
const val MESS_LINK = "https://drive.google.com/file/d/1C4fAedg5sJ78xzjMvGi46AJA-4TfKx5a/view?usp=sharing"
const val HOLIDAY_LINK = "https://drive.google.com/file/d/1CCFCfdhEJFHHg3TS_Y3d23haSdOk1YNg/view?usp=sharing"
const val CALENDER_LINK = "https://drive.google.com/file/d/1t2fTRz18dJcokEO0rFrctqs3kzQQuNDD/view?usp=sharing"
const val WARDEN_LINK = "https://drive.google.com/file/d/1zV0BDKMvTxhdpTKKK_wTpFRmlQ3FXrVx/view?usp=sharing"
const val Parent_Portal_Link = "https://parent.iitism.ac.in/index.php/parent_portal/portal0"
